// This file is auto-generated by @hey-api/openapi-ts

export const $RegisterDto = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'Username',
            example: 'johndoe1',
            minLength: 8
        },
        first_name: {
            type: 'string',
            description: 'User first name',
            example: 'John',
            minLength: 1
        },
        last_name: {
            type: 'string',
            description: 'User last name',
            example: 'Doe',
            minLength: 1
        },
        email: {
            type: 'string',
            description: 'User email',
            example: 'john.doe@example.com'
        },
        password: {
            type: 'string',
            description: 'User password',
            example: 'securePassword123'
        },
        confirm_password: {
            type: 'string',
            description: 'Password confirmation',
            example: 'securePassword123'
        },
        role: {
            type: 'string',
            description: 'User role',
            example: 'Pupil',
            enum: ['Pupil', 'Teacher']
        }
    },
    required: ['username', 'first_name', 'last_name', 'email', 'password', 'confirm_password', 'role']
} as const;

export const $UserResponseDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'User ID',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        email: {
            type: 'string',
            description: 'Email',
            nullable: true
        },
        first_name: {
            type: 'string',
            description: 'First name',
            nullable: true
        },
        last_name: {
            type: 'string',
            description: 'Last name',
            nullable: true
        },
        role: {
            type: 'string',
            description: 'User role',
            nullable: true
        },
        created_at: {
            format: 'date-time',
            type: 'string',
            description: 'Created at'
        },
        updated_at: {
            format: 'date-time',
            type: 'string',
            description: 'Created at'
        }
    },
    required: ['id', 'email', 'first_name', 'last_name', 'role']
} as const;

export const $AuthResponseDto = {
    type: 'object',
    properties: {
        access_token: {
            type: 'string',
            description: 'Access token'
        },
        user: {
            description: 'User info',
            allOf: [
                {
                    '$ref': '#/components/schemas/UserResponseDto'
                }
            ]
        },
        refresh_token: {
            type: 'string',
            description: 'Refresh token'
        }
    },
    required: ['access_token', 'user']
} as const;

export const $ErrorResponseDto = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            description: 'Status of the response',
            example: 'error'
        },
        message: {
            type: 'string',
            description: 'Error message',
            example: 'Invalid credentials'
        }
    },
    required: ['status', 'message']
} as const;

export const $LoginDto = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            description: 'User email',
            example: 'john.doe@example.com'
        },
        password: {
            type: 'string',
            description: 'User password',
            example: 'securePassword123'
        }
    },
    required: ['email', 'password']
} as const;

export const $SuccessResponseDto = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            description: 'Success message',
            example: 'User created successfully'
        },
        data: {
            type: 'object',
            description: 'Returned data payload'
        }
    },
    required: ['message', 'data']
} as const;

export const $RefreshTokenDto = {
    type: 'object',
    properties: {
        refresh_token: {
            type: 'string',
            description: 'Refresh token'
        }
    },
    required: ['refresh_token']
} as const;

export const $ForgotPasswordDto = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            description: 'User email',
            example: 'john.doe@example.com'
        }
    },
    required: ['email']
} as const;

export const $ResetPasswordDto = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            description: 'Reset token'
        },
        new_password: {
            type: 'string',
            description: 'New password',
            example: 'newSecurePassword123'
        }
    },
    required: ['token', 'new_password']
} as const;

export const $UpdateProfileDto = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'Username',
            example: 'janes123',
            minLength: 8
        },
        first_name: {
            type: 'string',
            description: 'First name',
            example: 'Jane'
        },
        last_name: {
            type: 'string',
            description: 'Last name',
            example: 'Smith'
        },
        email: {
            type: 'string',
            description: 'Email address'
        },
        avatar: {
            type: 'string',
            description: 'Avatar'
        }
    }
} as const;

export const $ChangePasswordDto = {
    type: 'object',
    properties: {
        current_password: {
            type: 'string',
            description: 'Current password'
        },
        new_password: {
            type: 'string',
            description: 'New password'
        }
    },
    required: ['current_password', 'new_password']
} as const;

export const $UpdatePupilProfileDto = {
    type: 'object',
    properties: {
        age: {
            type: 'number',
            description: 'Age',
            example: 10
        },
        grade_level: {
            type: 'number',
            description: 'Grade Level',
            example: 6
        }
    },
    required: ['age', 'grade_level']
} as const;

export const $CreateClassroomDto = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'Classroom Name',
            example: 'Section Maya'
        },
        description: {
            type: 'string',
            description: 'Classroom Name',
            example: 'Section Maya'
        }
    },
    required: ['name', 'description']
} as const;

export const $UpdateClassroomDto = {
    type: 'object',
    properties: {}
} as const;

export const $CreateMinigameLogDto = {
    type: 'object',
    properties: {
        minigame_id: {
            type: 'string',
            description: 'Minigame ID'
        },
        pupil_id: {
            type: 'string',
            description: 'Pupil ID'
        },
        reading_session_id: {
            type: 'string',
            description: 'Reading Session ID'
        },
        result: {
            type: 'string',
            description: 'Minigame Result in JSON format'
        }
    },
    required: ['minigame_id', 'pupil_id', 'reading_session_id', 'result']
} as const;