// This file is auto-generated by @hey-api/openapi-ts

export type RegisterDto = {
    /**
     * Username
     */
    username: string;
    /**
     * User first name
     */
    first_name: string;
    /**
     * User last name
     */
    last_name: string;
    /**
     * User email
     */
    email: string;
    /**
     * User password
     */
    password: string;
    /**
     * Password confirmation
     */
    confirm_password: string;
    /**
     * User role
     */
    role: 'Pupil' | 'Teacher';
};

export type UserResponseDto = {
    /**
     * User ID
     */
    id: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * First name
     */
    first_name: string | null;
    /**
     * Last name
     */
    last_name: string | null;
    /**
     * User role
     */
    role: string | null;
    /**
     * Created at
     */
    created_at?: string;
    /**
     * Created at
     */
    updated_at?: string;
};

export type AuthResponseDto = {
    /**
     * Access token
     */
    access_token: string;
    /**
     * User info
     */
    user: UserResponseDto;
    /**
     * Refresh token
     */
    refresh_token?: string;
};

export type ErrorResponseDto = {
    message: string;
    /**
     * Detailed error, if any
     */
    error?: string;
};

export type LoginDto = {
    /**
     * User email
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type SuccessResponseDto = {
    /**
     * Response status
     */
    status: string;
    message: string;
    /**
     * Response data
     */
    data: {
        [key: string]: unknown;
    };
};

export type GoogleExchangeTokenDto = {
    /**
     * Google ID Token
     */
    id_token: string;
};

export type RefreshTokenDto = {
    /**
     * Refresh token
     */
    refresh_token: string;
};

export type ForgotPasswordDto = {
    /**
     * User email
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * Reset token
     */
    token: string;
    /**
     * New password
     */
    new_password: string;
};

export type UpdateProfileDto = {
    /**
     * Username
     */
    username?: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
    /**
     * Email address
     */
    email?: string;
    /**
     * Avatar
     */
    avatar?: string;
};

export type ChangePasswordDto = {
    /**
     * Current password
     */
    current_password: string;
    /**
     * New password
     */
    new_password: string;
};

export type UpdatePupilProfileDto = {
    /**
     * Age
     */
    age: number;
    /**
     * Grade Level
     */
    grade_level: number;
};

export type CreateClassroomDto = {
    /**
     * Classroom Name
     */
    name: string;
    /**
     * Classroom Name
     */
    description: string;
};

export type EnrollPupilDto = {
    /**
     * Classroom Id
     */
    classroom_id: string;
    /**
     * Array of Pupil Ids
     */
    pupil_ids: Array<Array<unknown>>;
};

export type UnEnrollPupilDto = {
    /**
     * Classroom Id
     */
    classroom_id: string;
    /**
     * Array of Pupil Ids
     */
    pupil_ids: Array<Array<unknown>>;
};

export type JoinClassroomDto = {
    /**
     * Classroom Code
     */
    code: string;
};

export type LeaveClassroomDto = {
    /**
     * Classroom Id
     */
    classroom_id: string;
};

export type UpdateClassroomDto = {
    /**
     * Classroom Name
     */
    name?: string;
    /**
     * Classroom Name
     */
    description?: string;
};

export type CreateWordsFromLettersGame = {
    /**
     * Reading Material Id
     */
    reading_material_id: string;
    /**
     * Part number of where the minigame appears in the story. Always 10 for WordsFromLetters.
     */
    part_num: number;
    /**
     * Contains the letters needed in creating words.
     */
    letters: Array<string>;
    /**
     * Words that can be created from the letters list.
     */
    words: Array<string>;
};

export type ChoicesObject = {
    /**
     * Choice text
     */
    choice: string;
    /**
     * Whether this choice is correct
     */
    answer: boolean;
};

export type CreateChoicesGame = {
    /**
     * Reading Material Id
     */
    reading_material_id: string;
    /**
     * Part number of where the minigame appears in the story.
     */
    part_num: number;
    /**
     * Question
     */
    question: string;
    /**
     * List of choices.
     */
    choices: Array<ChoicesObject>;
    /**
     * Explanation of the answer.
     */
    explanation: string;
};

export type CreateSentenceRearrangementGame = {
    /**
     * Reading Material Id
     */
    reading_material_id: string;
    /**
     * Part number of where the minigame appears in the story.
     */
    part_num: number;
    /**
     * List of correct answers.
     */
    correct_answer: Array<string>;
    /**
     * Sentence parts
     */
    parts: Array<string>;
    /**
     * Explanation of the answer.
     */
    explanation: string;
};

export type CreateMinigameLogDto = {
    /**
     * Minigame ID
     */
    minigame_id: string;
    /**
     * Pupil ID
     */
    pupil_id: string;
    /**
     * Reading Session ID
     */
    reading_session_id: string;
    /**
     * Minigame Result in JSON format
     */
    result: string;
};

export type CreateReadingSessionDto = {
    /**
     * Reading material id
     */
    reading_material_id: string;
};

export type UpdateReadingSessionDto = {
    /**
     * Completion percentage of the reading session
     */
    completion_percentage: number;
};

export type CreateReadingMaterialDto = {
    /**
     * Source of the reading material
     */
    is_deped: boolean;
    /**
     * Title of the reading material
     */
    title: string;
    /**
     * Author of the reading material
     */
    author: string;
    /**
     * Description of the reading material
     */
    description: string;
    /**
     * Grade level for which the reading material is suitable
     */
    grade_level: number;
    /**
     * Cover link image URL for the reading material
     */
    cover: string;
    /**
     * List of genre for the reading material
     */
    genres: Array<string>;
    /**
     * Content of the reading material
     */
    content: string;
};

export type CreateGenreDto = {
    /**
     * Name of the genre
     */
    name: string;
};

export type CreateActivityDto = {
    /**
     * Activity Name
     */
    title: string;
    /**
     * Description on what the activity is about
     */
    description?: string;
    reading_material_id: string;
};

export type UpdateActivityDto = {
    /**
     * Activity Name
     */
    title?: string;
    /**
     * Description on what the activity is about
     */
    description?: string;
    reading_material_id?: string;
};

export type CreateActivityLogDto = {
    /**
     * Minigame log Id
     */
    minigame_log_id: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AppControllerHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppControllerHealthCheckResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    /**
     * User registration data
     */
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Invalid input data
     */
    400: ErrorResponseDto;
    /**
     * User already exists
     */
    409: ErrorResponseDto;
};

export type AuthControllerRegisterError = AuthControllerRegisterErrors[keyof AuthControllerRegisterErrors];

export type AuthControllerRegisterResponses = {
    /**
     * User successfully registered
     */
    201: AuthResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    /**
     * User login credentials
     */
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Invalid input data
     */
    400: ErrorResponseDto;
    /**
     * Invalid credentials
     */
    401: ErrorResponseDto;
};

export type AuthControllerLoginError = AuthControllerLoginErrors[keyof AuthControllerLoginErrors];

export type AuthControllerLoginResponses = {
    /**
     * User successfully logged in
     */
    200: SuccessResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerExchangeGoogleIdTokenData = {
    body: GoogleExchangeTokenDto;
    path?: never;
    query?: never;
    url: '/auth/google/token';
};

export type AuthControllerExchangeGoogleIdTokenResponses = {
    200: SuccessResponseDto;
};

export type AuthControllerExchangeGoogleIdTokenResponse = AuthControllerExchangeGoogleIdTokenResponses[keyof AuthControllerExchangeGoogleIdTokenResponses];

export type AuthControllerRefreshTokenData = {
    /**
     * Refresh token
     */
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshTokenErrors = {
    /**
     * Invalid refresh token
     */
    401: ErrorResponseDto;
};

export type AuthControllerRefreshTokenError = AuthControllerRefreshTokenErrors[keyof AuthControllerRefreshTokenErrors];

export type AuthControllerRefreshTokenResponses = {
    /**
     * Token refreshed successfully
     */
    200: SuccessResponseDto;
};

export type AuthControllerRefreshTokenResponse = AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type AuthControllerForgotPasswordData = {
    /**
     * User email for password reset
     */
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordErrors = {
    /**
     * Invalid input data
     */
    400: ErrorResponseDto;
};

export type AuthControllerForgotPasswordError = AuthControllerForgotPasswordErrors[keyof AuthControllerForgotPasswordErrors];

export type AuthControllerForgotPasswordResponses = {
    /**
     * Password reset email sent (if email exists)
     */
    200: SuccessResponseDto;
};

export type AuthControllerForgotPasswordResponse = AuthControllerForgotPasswordResponses[keyof AuthControllerForgotPasswordResponses];

export type AuthControllerResetPasswordData = {
    /**
     * Reset token and new password
     */
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Invalid or expired reset token
     */
    400: ErrorResponseDto;
};

export type AuthControllerResetPasswordError = AuthControllerResetPasswordErrors[keyof AuthControllerResetPasswordErrors];

export type AuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: SuccessResponseDto;
};

export type AuthControllerResetPasswordResponse = AuthControllerResetPasswordResponses[keyof AuthControllerResetPasswordResponses];

export type AuthControllerRequestEmailVerificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/request-email-verification';
};

export type AuthControllerRequestEmailVerificationResponses = {
    /**
     * Email verication sent.
     */
    200: SuccessResponseDto;
};

export type AuthControllerRequestEmailVerificationResponse = AuthControllerRequestEmailVerificationResponses[keyof AuthControllerRequestEmailVerificationResponses];

export type AuthControllerVerifyEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email verification token
         */
        token: string;
    };
    url: '/auth/verify-email';
};

export type AuthControllerVerifyEmailErrors = {
    /**
     * Invalid or expired verification token
     */
    400: ErrorResponseDto;
};

export type AuthControllerVerifyEmailError = AuthControllerVerifyEmailErrors[keyof AuthControllerVerifyEmailErrors];

export type AuthControllerVerifyEmailResponses = {
    /**
     * Email verified successfully
     */
    200: SuccessResponseDto;
};

export type AuthControllerVerifyEmailResponse = AuthControllerVerifyEmailResponses[keyof AuthControllerVerifyEmailResponses];

export type AuthControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerGetProfileErrors = {
    /**
     * Invalid or missing token
     */
    401: ErrorResponseDto;
};

export type AuthControllerGetProfileError = AuthControllerGetProfileErrors[keyof AuthControllerGetProfileErrors];

export type AuthControllerGetProfileResponses = {
    /**
     * User profile retrieved successfully
     */
    200: SuccessResponseDto;
};

export type AuthControllerGetProfileResponse = AuthControllerGetProfileResponses[keyof AuthControllerGetProfileResponses];

export type AuthControllerUpdateProfileData = {
    /**
     * Profile update data
     */
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerUpdateProfileErrors = {
    /**
     * Invalid or missing token
     */
    401: ErrorResponseDto;
    /**
     * Email already exists
     */
    409: ErrorResponseDto;
};

export type AuthControllerUpdateProfileError = AuthControllerUpdateProfileErrors[keyof AuthControllerUpdateProfileErrors];

export type AuthControllerUpdateProfileResponses = {
    /**
     * Profile updated successfully
     */
    200: SuccessResponseDto;
};

export type AuthControllerUpdateProfileResponse = AuthControllerUpdateProfileResponses[keyof AuthControllerUpdateProfileResponses];

export type AuthControllerChangePasswordData = {
    /**
     * Current and new password
     */
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type AuthControllerChangePasswordErrors = {
    /**
     * Invalid or missing token / Current password incorrect
     */
    401: ErrorResponseDto;
};

export type AuthControllerChangePasswordError = AuthControllerChangePasswordErrors[keyof AuthControllerChangePasswordErrors];

export type AuthControllerChangePasswordResponses = {
    /**
     * Password changed successfully
     */
    200: SuccessResponseDto;
};

export type AuthControllerChangePasswordResponse = AuthControllerChangePasswordResponses[keyof AuthControllerChangePasswordResponses];

export type AuthControllerLogoutData = {
    /**
     * Optional refresh token to revoke
     */
    body?: {
        refresh_token?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutErrors = {
    /**
     * Invalid or missing token
     */
    401: ErrorResponseDto;
};

export type AuthControllerLogoutError = AuthControllerLogoutErrors[keyof AuthControllerLogoutErrors];

export type AuthControllerLogoutResponses = {
    /**
     * User successfully logged out
     */
    200: SuccessResponseDto;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type AuthControllerVerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/verify-token';
};

export type AuthControllerVerifyTokenErrors = {
    /**
     * Invalid or expired token
     */
    401: ErrorResponseDto;
};

export type AuthControllerVerifyTokenError = AuthControllerVerifyTokenErrors[keyof AuthControllerVerifyTokenErrors];

export type AuthControllerVerifyTokenResponses = {
    /**
     * Token is valid
     */
    200: {
        valid?: boolean;
        user?: UserResponseDto;
    };
};

export type AuthControllerVerifyTokenResponse = AuthControllerVerifyTokenResponses[keyof AuthControllerVerifyTokenResponses];

export type AuthControllerGetProfileLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/profile';
};

export type AuthControllerGetProfileLegacyErrors = {
    /**
     * Invalid or missing token
     */
    401: ErrorResponseDto;
};

export type AuthControllerGetProfileLegacyError = AuthControllerGetProfileLegacyErrors[keyof AuthControllerGetProfileLegacyErrors];

export type AuthControllerGetProfileLegacyResponses = {
    /**
     * User profile retrieved successfully
     */
    200: UserResponseDto;
};

export type AuthControllerGetProfileLegacyResponse = AuthControllerGetProfileLegacyResponses[keyof AuthControllerGetProfileLegacyResponses];

export type PupilsControllerGetPupilProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pupils/me';
};

export type PupilsControllerGetPupilProfileErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseDto;
};

export type PupilsControllerGetPupilProfileError = PupilsControllerGetPupilProfileErrors[keyof PupilsControllerGetPupilProfileErrors];

export type PupilsControllerGetPupilProfileResponses = {
    /**
     * Pupil profile successfully fetched
     */
    201: SuccessResponseDto;
};

export type PupilsControllerGetPupilProfileResponse = PupilsControllerGetPupilProfileResponses[keyof PupilsControllerGetPupilProfileResponses];

export type PupilsControllerUpdatePupilProfileData = {
    /**
     * Pupil profile update data
     */
    body: UpdatePupilProfileDto;
    path?: never;
    query?: never;
    url: '/pupils/me';
};

export type PupilsControllerUpdatePupilProfileErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseDto;
};

export type PupilsControllerUpdatePupilProfileError = PupilsControllerUpdatePupilProfileErrors[keyof PupilsControllerUpdatePupilProfileErrors];

export type PupilsControllerUpdatePupilProfileResponses = {
    /**
     * Pupil profile successfully updated
     */
    201: SuccessResponseDto;
};

export type PupilsControllerUpdatePupilProfileResponse = PupilsControllerUpdatePupilProfileResponses[keyof PupilsControllerUpdatePupilProfileResponses];

export type PupilsControllerGetPupilByUsernameData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/pupils/{username}';
};

export type PupilsControllerGetPupilByUsernameErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseDto;
};

export type PupilsControllerGetPupilByUsernameError = PupilsControllerGetPupilByUsernameErrors[keyof PupilsControllerGetPupilByUsernameErrors];

export type PupilsControllerGetPupilByUsernameResponses = {
    /**
     * Pupil profile successfully fetched
     */
    201: SuccessResponseDto;
};

export type PupilsControllerGetPupilByUsernameResponse = PupilsControllerGetPupilByUsernameResponses[keyof PupilsControllerGetPupilByUsernameResponses];

export type PupilsControllerGetGlobalPupilLeaderboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pupils/leaderboard';
};

export type PupilsControllerGetGlobalPupilLeaderboardErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseDto;
};

export type PupilsControllerGetGlobalPupilLeaderboardError = PupilsControllerGetGlobalPupilLeaderboardErrors[keyof PupilsControllerGetGlobalPupilLeaderboardErrors];

export type PupilsControllerGetGlobalPupilLeaderboardResponses = {
    /**
     * Global pupil leaderboard successfully fetched
     */
    201: SuccessResponseDto;
};

export type PupilsControllerGetGlobalPupilLeaderboardResponse = PupilsControllerGetGlobalPupilLeaderboardResponses[keyof PupilsControllerGetGlobalPupilLeaderboardResponses];

export type PupilsControllerGetPupilLeaderBoardByPupilIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pupils/leaderboard/{pupilId}';
};

export type PupilsControllerGetPupilLeaderBoardByPupilIdErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseDto;
};

export type PupilsControllerGetPupilLeaderBoardByPupilIdError = PupilsControllerGetPupilLeaderBoardByPupilIdErrors[keyof PupilsControllerGetPupilLeaderBoardByPupilIdErrors];

export type PupilsControllerGetPupilLeaderBoardByPupilIdResponses = {
    /**
     * Pupil leaderboard successfully fetched
     */
    201: SuccessResponseDto;
};

export type PupilsControllerGetPupilLeaderBoardByPupilIdResponse = PupilsControllerGetPupilLeaderBoardByPupilIdResponses[keyof PupilsControllerGetPupilLeaderBoardByPupilIdResponses];

export type ClassroomsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/classrooms';
};

export type ClassroomsControllerFindAllResponses = {
    200: unknown;
};

export type ClassroomsControllerCreateData = {
    body: CreateClassroomDto;
    path?: never;
    query?: never;
    url: '/classrooms';
};

export type ClassroomsControllerCreateResponses = {
    201: unknown;
};

export type ClassroomsControllerEnrollData = {
    body: EnrollPupilDto;
    path?: never;
    query?: never;
    url: '/classrooms/enroll';
};

export type ClassroomsControllerEnrollResponses = {
    201: unknown;
};

export type ClassroomsControllerUnEnrollData = {
    body: UnEnrollPupilDto;
    path?: never;
    query?: never;
    url: '/classrooms/unenroll';
};

export type ClassroomsControllerUnEnrollResponses = {
    201: unknown;
};

export type ClassroomsControllerJoinData = {
    body: JoinClassroomDto;
    path?: never;
    query?: never;
    url: '/classrooms/join';
};

export type ClassroomsControllerJoinResponses = {
    201: unknown;
};

export type ClassroomsControllerLeaveData = {
    body: LeaveClassroomDto;
    path?: never;
    query?: never;
    url: '/classrooms/leave';
};

export type ClassroomsControllerLeaveResponses = {
    201: unknown;
};

export type ClassroomsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/classrooms/{id}';
};

export type ClassroomsControllerRemoveResponses = {
    200: unknown;
};

export type ClassroomsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/classrooms/{id}';
};

export type ClassroomsControllerFindOneResponses = {
    200: unknown;
};

export type ClassroomsControllerUpdateData = {
    body: UpdateClassroomDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/classrooms/{id}';
};

export type ClassroomsControllerUpdateResponses = {
    200: unknown;
};

export type MinigamesControllerCreateWflMinigameData = {
    body: CreateWordsFromLettersGame;
    path?: never;
    query?: never;
    url: '/minigames/wordsFromLetters';
};

export type MinigamesControllerCreateWflMinigameResponses = {
    201: unknown;
};

export type MinigamesControllerCreateChoicesMinigameData = {
    body: CreateChoicesGame;
    path?: never;
    query?: never;
    url: '/minigames/choices';
};

export type MinigamesControllerCreateChoicesMinigameResponses = {
    201: unknown;
};

export type MinigamesControllerCreateSrMinigameData = {
    body: CreateSentenceRearrangementGame;
    path?: never;
    query?: never;
    url: '/minigames/sentenceRearrangement';
};

export type MinigamesControllerCreateSrMinigameResponses = {
    201: unknown;
};

export type MinigamesControllerFindMinigamesByMaterialIdData = {
    body?: never;
    path: {
        readingMaterialID: string;
    };
    query?: never;
    url: '/minigames/readingmaterials/{readingMaterialID}/random';
};

export type MinigamesControllerFindMinigamesByMaterialIdResponses = {
    200: unknown;
};

export type MinigamesControllerFindMinigamesBySessionIdData = {
    body?: never;
    path: {
        readingSessionID: string;
    };
    query?: never;
    url: '/minigames/{readingSessionID}/random';
};

export type MinigamesControllerFindMinigamesBySessionIdResponses = {
    200: unknown;
};

export type MinigamesControllerFindWordsFromLettersMinigameData = {
    body?: never;
    path: {
        readingMaterialID: string;
    };
    query?: never;
    url: '/minigames/{readingMaterialID}/wordsFromLetters';
};

export type MinigamesControllerFindWordsFromLettersMinigameResponses = {
    200: unknown;
};

export type MinigamesControllerGetMinigamesCompletionData = {
    body?: never;
    path: {
        readingSessionID: string;
    };
    query?: never;
    url: '/minigames/{readingSessionID}/complete';
};

export type MinigamesControllerGetMinigamesCompletionResponses = {
    201: unknown;
};

export type MinigamesControllerCreateSentenceRearrangementLogData = {
    body: CreateMinigameLogDto;
    path?: never;
    query?: never;
    url: '/minigames/logs/SentenceRearrangement';
};

export type MinigamesControllerCreateSentenceRearrangementLogResponses = {
    201: unknown;
};

export type MinigamesControllerCreateChoicesLogData = {
    body: CreateMinigameLogDto;
    path?: never;
    query?: never;
    url: '/minigames/logs/Choices';
};

export type MinigamesControllerCreateChoicesLogResponses = {
    201: unknown;
};

export type MinigamesControllerCreateWordsFromLettersLogData = {
    body: CreateMinigameLogDto;
    path?: never;
    query?: never;
    url: '/minigames/logs/WordsFromLetters';
};

export type MinigamesControllerCreateWordsFromLettersLogResponses = {
    201: unknown;
};

export type ReadingSessionsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reading-sessions';
};

export type ReadingSessionsControllerFindAllResponses = {
    200: unknown;
};

export type ReadingSessionsControllerCreateData = {
    body: CreateReadingSessionDto;
    path?: never;
    query?: never;
    url: '/reading-sessions';
};

export type ReadingSessionsControllerCreateResponses = {
    201: unknown;
};

export type ReadingSessionsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reading-sessions/{id}';
};

export type ReadingSessionsControllerRemoveResponses = {
    200: unknown;
};

export type ReadingSessionsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reading-sessions/{id}';
};

export type ReadingSessionsControllerFindOneResponses = {
    200: unknown;
};

export type ReadingSessionsControllerUpdateData = {
    body: UpdateReadingSessionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/reading-sessions/{id}';
};

export type ReadingSessionsControllerUpdateResponses = {
    200: unknown;
};

export type ReadingMaterialsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reading-materials';
};

export type ReadingMaterialsControllerFindAllResponses = {
    200: unknown;
};

export type ReadingMaterialsControllerCreateData = {
    body: CreateReadingMaterialDto;
    path?: never;
    query?: never;
    url: '/reading-materials';
};

export type ReadingMaterialsControllerCreateResponses = {
    201: unknown;
};

export type ReadingMaterialsControllerFindRecommendationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reading-materials/recommendations';
};

export type ReadingMaterialsControllerFindRecommendationsResponses = {
    200: unknown;
};

export type ReadingMaterialsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reading-materials/{id}';
};

export type ReadingMaterialsControllerFindOneResponses = {
    200: unknown;
};

export type GenresControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/genres';
};

export type GenresControllerFindAllResponses = {
    200: unknown;
};

export type GenresControllerCreateData = {
    body: CreateGenreDto;
    path?: never;
    query?: never;
    url: '/genres';
};

export type GenresControllerCreateResponses = {
    201: unknown;
};

export type AchievementsControllerGetPupilAchievementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/achievements';
};

export type AchievementsControllerGetPupilAchievementsResponses = {
    200: unknown;
};

export type AchievementsControllerAddPupilAchievementData = {
    body?: never;
    path: {
        pupilId: string;
        achievementName: string;
    };
    query?: never;
    url: '/achievements/pupil/{pupilId}/achievement/{achievementName}';
};

export type AchievementsControllerAddPupilAchievementResponses = {
    201: unknown;
};

export type AchievementsControllerGetPupilAchievementsByIdData = {
    body?: never;
    path: {
        pupilId: string;
    };
    query?: never;
    url: '/achievements/pupils/{pupilId}';
};

export type AchievementsControllerGetPupilAchievementsByIdResponses = {
    200: unknown;
};

export type AchievementsControllerRemovePupilAchievementData = {
    body?: never;
    path: {
        pupilId: string;
        achievementId: string;
    };
    query?: never;
    url: '/achievements/pupils/{pupilId}/achievements/{achievementId}';
};

export type AchievementsControllerRemovePupilAchievementResponses = {
    200: unknown;
};

export type AchievementsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/achievements/{id}';
};

export type AchievementsControllerRemoveResponses = {
    200: unknown;
};

export type ActivityControllerFindAllByClassroomIdData = {
    body?: never;
    path: {
        classroomId: string;
    };
    query?: never;
    url: '/classrooms/{classroomId}/activity';
};

export type ActivityControllerFindAllByClassroomIdResponses = {
    200: unknown;
};

export type ActivityControllerCreateData = {
    body: CreateActivityDto;
    path: {
        classroomId: string;
    };
    query?: never;
    url: '/classrooms/{classroomId}/activity';
};

export type ActivityControllerCreateResponses = {
    201: unknown;
};

export type ActivityControllerRemoveData = {
    body?: never;
    path: {
        activityId: string;
    };
    query?: never;
    url: '/classrooms/{classroomId}/activity/{activityId}';
};

export type ActivityControllerRemoveResponses = {
    200: unknown;
};

export type ActivityControllerFindOneData = {
    body?: never;
    path: {
        activityId: string;
    };
    query?: never;
    url: '/classrooms/{classroomId}/activity/{activityId}';
};

export type ActivityControllerFindOneResponses = {
    200: unknown;
};

export type ActivityControllerUpdateData = {
    body: UpdateActivityDto;
    path: {
        activityId: string;
    };
    query?: never;
    url: '/classrooms/{classroomId}/activity/{activityId}';
};

export type ActivityControllerUpdateResponses = {
    200: unknown;
};

export type UserControllerGetLoginStreakData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me/streak';
};

export type UserControllerGetLoginStreakResponses = {
    200: unknown;
};

export type UserControllerUpdateLoginStreakData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me/streak';
};

export type UserControllerUpdateLoginStreakResponses = {
    200: unknown;
};

export type UserControllerGetTotalSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me/sessions';
};

export type UserControllerGetTotalSessionsResponses = {
    200: unknown;
};

export type UserControllerCreateSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me/sessions';
};

export type UserControllerCreateSessionResponses = {
    201: unknown;
};

export type UserControllerEndSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/user/me/sessions/{sessionId}';
};

export type UserControllerEndSessionResponses = {
    200: unknown;
};

export type UserControllerSearchUsersData = {
    body?: never;
    path?: never;
    query: {
        query: string;
        role: string;
    };
    url: '/user/search';
};

export type UserControllerSearchUsersResponses = {
    200: unknown;
};

export type ActivityLogsControllerFindOneData = {
    body?: never;
    path: {
        activityId: string;
    };
    query?: never;
    url: '/classroom/activity-logs/{activityId}';
};

export type ActivityLogsControllerFindOneResponses = {
    200: unknown;
};

export type ActivityLogsControllerCreateData = {
    body: CreateActivityLogDto;
    path: {
        '/activityId': string;
    };
    query?: never;
    url: '/classroom/activity-logs/{activityId}';
};

export type ActivityLogsControllerCreateResponses = {
    201: unknown;
};

export type ActivityLogsControllerFindAllData = {
    body?: never;
    path: {
        classroomId: string;
    };
    query?: never;
    url: '/classroom/activity-logs/{activityId}/classroom/{classroomId}/activity-logs';
};

export type ActivityLogsControllerFindAllResponses = {
    200: unknown;
};

export type DictionaryControllerDefinitionData = {
    body?: never;
    path: {
        word: string;
    };
    query?: never;
    url: '/dictionary/dictionary/{word}';
};

export type DictionaryControllerDefinitionResponses = {
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};
