/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type StorageBuckettype = "ANALYTICS" | "STANDARD";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Achievements {
  badge: string | null;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string>;
  name: string | null;
}

export interface Activities {
  classroom_id: string | null;
  description: string | null;
  id: Generated<string>;
  reading_material_id: string | null;
  title: string | null;
}

export interface ActivityLogs {
  activity_id: string | null;
  completed_at: Timestamp | null;
  id: Generated<string>;
  minigame_log_id: string | null;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthenticationAuthProviders {
  access_token: string | null;
  created_at: Generated<Timestamp | null>;
  email: string | null;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  password_hash: string | null;
  provider_type: string;
  provider_user_id: string | null;
  refresh_token: string | null;
  token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
}

export interface AuthenticationEmailVerificationTokens {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  token: string;
  used: boolean;
  user_id: string;
}

export interface AuthenticationLoginStreaks {
  current_streak: number | null;
  id: Generated<string>;
  last_login_date: Generated<Timestamp | null>;
  longest_streak: number | null;
  user_id: string | null;
}

export interface AuthenticationPasswordResetTokens {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  token: string;
  used: boolean;
  user_id: string;
}

export interface AuthenticationPermissions {
  description: string | null;
  id: Generated<string>;
  name: string;
}

export interface AuthenticationRefreshTokens {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked: boolean;
  token: string;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface AuthenticationRolePermissions {
  permission_id: string;
  role_id: number;
}

export interface AuthenticationRoles {
  description: string | null;
  id: Generated<number>;
  name: string;
}

export interface AuthenticationSessions {
  created_at: Generated<Timestamp | null>;
  duration: number | null;
  end_at: Timestamp | null;
  id: Generated<string>;
  user_id: string | null;
}

export interface AuthenticationUserRoles {
  role_id: number;
  user_id: string;
}

export interface AuthenticationUsers {
  avatar: string | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  first_name: string;
  id: Generated<string>;
  is_deleted: Generated<boolean | null>;
  is_email_verified: boolean | null;
  is_phone_verified: boolean | null;
  last_name: string;
  phone: string | null;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface AuthFlowState {
  auth_code: string;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string;
  code_challenge_method: AuthCodeChallengeMethod;
  created_at: Timestamp | null;
  id: string;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthClients {
  client_id: string;
  client_name: string | null;
  client_secret_hash: string;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  updated_at: Generated<Timestamp>;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  refreshed_at: Timestamp | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface ClassroomEnrollment {
  classroom_id: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  pupil_id: string;
}

export interface Classrooms {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string>;
  join_code: string | null;
  name: string;
  teacher_id: string;
  updated_at: Timestamp | null;
}

export interface ClassroomView {
  created_at: Timestamp | null;
  description: string | null;
  id: string | null;
  join_code: string | null;
  name: string | null;
  pupil_count: Int8 | null;
  teacher_first_name: string | null;
  teacher_id: string | null;
  teacher_last_name: string | null;
  updated_at: Timestamp | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Genres {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  name: string | null;
}

export interface LibraryEntries {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reading_material_id: string | null;
  user_id: string | null;
}

export interface MinigameLogs {
  created_at: Timestamp | null;
  id: Generated<string>;
  minigame_id: string | null;
  reading_session_id: string | null;
  result: string | null;
}

export interface Minigames {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  max_score: number | null;
  metadata: string | null;
  minigame_type: number | null;
  part_num: number | null;
  reading_material_id: string | null;
}

export interface PupilAchievements {
  achievement_id: string | null;
  created_at: Timestamp | null;
  id: Generated<string>;
  pupil_id: string | null;
}

export interface PupilLeaderboard {
  id: Generated<string>;
  level: number;
  pupil_id: string;
  recorded_at: Timestamp;
}

export interface Pupils {
  age: number | null;
  created_at: Generated<Timestamp | null>;
  grade_level: number | null;
  id: Generated<string>;
  level: Generated<number | null>;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface ReadingMaterialGenres {
  genre_id: string | null;
  id: Generated<string>;
  reading_material_id: string | null;
}

export interface ReadingMaterials {
  author: string | null;
  content: string | null;
  cover: string | null;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  difficulty: number | null;
  grade_level: number | null;
  id: Generated<string>;
  is_deped: boolean | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface ReadingSessions {
  completed_at: Timestamp | null;
  completion_percentage: Generated<number | null>;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  pupil_id: string | null;
  reading_material_id: string | null;
  started_at: Generated<Timestamp | null>;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscription_id: string;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>;
  format: Generated<string>;
  id: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_accessed_at: Generated<Timestamp | null>;
  level: number | null;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StoragePrefixes {
  bucket_id: string;
  created_at: Generated<Timestamp | null>;
  level: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface Teachers {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  'public.achievements': Achievements;
  'public.activities': Activities;
  'public.activity_logs': ActivityLogs;
  'auth.audit_log_entries': AuthAuditLogEntries;
  'auth.flow_state': AuthFlowState;
  'auth.identities': AuthIdentities;
  'auth.instances': AuthInstances;
  'auth.mfa_amr_claims': AuthMfaAmrClaims;
  'auth.mfa_challenges': AuthMfaChallenges;
  'auth.mfa_factors': AuthMfaFactors;
  'auth.oauth_clients': AuthOauthClients;
  'auth.one_time_tokens': AuthOneTimeTokens;
  'auth.refresh_tokens': AuthRefreshTokens;
  'auth.saml_providers': AuthSamlProviders;
  'auth.saml_relay_states': AuthSamlRelayStates;
  'auth.schema_migrations': AuthSchemaMigrations;
  'auth.sessions': AuthSessions;
  'auth.sso_domains': AuthSsoDomains;
  'auth.sso_providers': AuthSsoProviders;
  'auth.users': AuthUsers;
  'authentication.auth_providers': AuthenticationAuthProviders;
  'authentication.email_verification_tokens': AuthenticationEmailVerificationTokens;
  'authentication.login_streaks': AuthenticationLoginStreaks;
  'authentication.password_reset_tokens': AuthenticationPasswordResetTokens;
  'authentication.permissions': AuthenticationPermissions;
  'authentication.refresh_tokens': AuthenticationRefreshTokens;
  'authentication.role_permissions': AuthenticationRolePermissions;
  'authentication.roles': AuthenticationRoles;
  'authentication.sessions': AuthenticationSessions;
  'authentication.user_roles': AuthenticationUserRoles;
  'authentication.users': AuthenticationUsers;
  'public.classroom_enrollment': ClassroomEnrollment;
  'public.classroom_view': ClassroomView;
  'public.classrooms': Classrooms;
  'extensions.pg_stat_statements': ExtensionsPgStatStatements;
  'extensions.pg_stat_statements_info': ExtensionsPgStatStatementsInfo;
  'public.genres': Genres;
  'public.library_entries': LibraryEntries;
  'public.minigame_logs': MinigameLogs;
  'public.minigames': Minigames;
  'public.pupil_achievements': PupilAchievements;
  'public.pupil_leaderboard': PupilLeaderboard;
  'public.pupils': Pupils;
  'public.reading_material_genres': ReadingMaterialGenres;
  'public.reading_materials': ReadingMaterials;
  'public.reading_sessions': ReadingSessions;
  'realtime.messages': RealtimeMessages;
  'realtime.schema_migrations': RealtimeSchemaMigrations;
  'realtime.subscription': RealtimeSubscription;
  'storage.buckets': StorageBuckets;
  'storage.buckets_analytics': StorageBucketsAnalytics;
  'storage.migrations': StorageMigrations;
  'storage.objects': StorageObjects;
  'storage.prefixes': StoragePrefixes;
  'storage.s3_multipart_uploads': StorageS3MultipartUploads;
  'storage.s3_multipart_uploads_parts': StorageS3MultipartUploadsParts;
  'public.teachers': Teachers;
  'vault.decrypted_secrets': VaultDecryptedSecrets;
  'vault.secrets': VaultSecrets;
}
